title:	Awayto.dev
baseURL: https://awayto.dev
languageCode: en-us
enableRobotsTXT: true

Params:
  appURL: https://awayto.exchange 
  v1Repo: https://github.com/keybittech/awayto
  v2Repo: https://github.com/keybittech/awayto-v2
  v3Repo: https://github.com/keybittech/awayto-v3

menu:
  main:
    - identifier: docs/0.3.0
      name: 0.3.0
      url: /docs/0.3.0/
      weight: 010
    - identifier: docs/0.2.0
      name: 0.2.0
      url: /docs/0.2.0/
      weight: 020
    - identifier: docs/0.1.0
      name: 0.1.0
      url: /docs/0.1.0/
      weight: 030
    
